services:
  - type: web
    name: podtranscode
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y ffmpeg
    startCommand: gunicorn web_app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
